import type { Bakery, CheckIn, Pastry, Profile } from "@/types/database";

export const BAKERIES: Bakery[] = [
	{
		id: "b001",
		name: "Porto's Bakery & Cafe",
		slug: "portos-bakery",
		address: "3614 W Magnolia Blvd",
		city: "Burbank, CA",
		country: "US",
		latitude: 34.1808,
		longitude: -118.309,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b002",
		name: "République",
		slug: "republique-la",
		address: "624 S La Brea Ave",
		city: "Los Angeles, CA",
		country: "US",
		latitude: 34.0632,
		longitude: -118.3444,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b003",
		name: "Fondry",
		slug: "fondry",
		address: "1633 Colorado Blvd",
		city: "Eagle Rock, CA",
		country: "US",
		latitude: 34.1375,
		longitude: -118.2117,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b004",
		name: "Modu Cafe",
		slug: "modu-cafe",
		address: "5043 York Blvd",
		city: "Highland Park, CA",
		country: "US",
		latitude: 34.1112,
		longitude: -118.2019,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b005",
		name: "Tu Cha",
		slug: "tu-cha",
		address: "621 S Western Ave #208",
		city: "Los Angeles, CA",
		country: "US",
		latitude: 34.062,
		longitude: -118.3089,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b006",
		name: "Lou, The French On The Block",
		slug: "lou-french",
		address: "1604 Sunset Blvd",
		city: "Los Angeles, CA",
		country: "US",
		latitude: 34.0775,
		longitude: -118.2535,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b007",
		name: "Arsicault Bakery",
		slug: "arsicault-bakery",
		address: "397 Arguello Blvd",
		city: "San Francisco, CA",
		country: "US",
		latitude: 37.7833,
		longitude: -122.4593,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b008",
		name: "B Patisserie",
		slug: "b-patisserie",
		address: "2821 California St",
		city: "San Francisco, CA",
		country: "US",
		latitude: 37.7878,
		longitude: -122.4402,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b009",
		name: "Tartine Bakery",
		slug: "tartine-bakery",
		address: "600 Guerrero St",
		city: "San Francisco, CA",
		country: "US",
		latitude: 37.7614,
		longitude: -122.4241,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b010",
		name: "Butter & Crumble",
		slug: "butter-crumble",
		address: "346 Columbus Ave",
		city: "San Francisco, CA",
		country: "US",
		latitude: 37.7983,
		longitude: -122.4074,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b011",
		name: "Grand Opening",
		slug: "grand-opening-sf",
		address: "1489 Webster St",
		city: "San Francisco, CA",
		country: "US",
		latitude: 37.7836,
		longitude: -122.4316,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b012",
		name: "Third Culture Bakery",
		slug: "third-culture",
		address: "2222 Fourth St",
		city: "Berkeley, CA",
		country: "US",
		latitude: 37.8716,
		longitude: -122.2975,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b013",
		name: "Golden Gate Bakery",
		slug: "golden-gate-bakery",
		address: "1029 Grant Ave",
		city: "San Francisco, CA",
		country: "US",
		latitude: 37.7963,
		longitude: -122.4077,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b014",
		name: "Cream Pan",
		slug: "cream-pan",
		address: "602 El Camino Real",
		city: "Tustin, CA",
		country: "US",
		latitude: 33.7463,
		longitude: -117.8264,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "b015",
		name: "61 Hundred Bread",
		slug: "61-hundred-bread",
		address: "220 E 4th St",
		city: "Santa Ana, CA",
		country: "US",
		latitude: 33.7468,
		longitude: -117.868,
		google_place_id: null,
		photo_url: null,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
];

export const PASTRIES: Pastry[] = [
	// Porto's
	{
		id: "p001",
		name: "Refugiado® (Guava & Cheese Strudel)",
		slug: "refugiado-guava-cheese",
		bakery_id: "b001",
		category: "Pastries",
		description:
			"Flaky puff pastry filled with sweet guava and cream cheese. The thing people stock up on.",
		photo_url: null,
		avg_rating: 4.8,
		total_checkins: 342,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p002",
		name: "Cheese Roll®",
		slug: "cheese-roll",
		bakery_id: "b001",
		category: "Bread",
		description:
			"Cream cheese-filled puff pastry with caramelized sugar crust. Addictively buttery.",
		photo_url: null,
		avg_rating: 4.7,
		total_checkins: 289,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p003",
		name: "Potato Ball® (Papa Rellena)",
		slug: "potato-ball",
		bakery_id: "b001",
		category: "Empanadas",
		description: "Crispy panko-crusted ball stuffed with seasoned picadillo. Savory perfection.",
		photo_url: null,
		avg_rating: 4.6,
		total_checkins: 256,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p004",
		name: "Dulce de Leche Besito® Cookie",
		slug: "dulce-de-leche-besito",
		bakery_id: "b001",
		category: "Cookies",
		description: "Shortbread cookie sandwiched with dulce de leche cream.",
		photo_url: null,
		avg_rating: 4.4,
		total_checkins: 128,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p005",
		name: "Milk'N Berries® Cake",
		slug: "milk-n-berries-cake",
		bakery_id: "b001",
		category: "Cakes",
		description: "Light sponge with fresh berries and whipped cream. Porto's bestselling cake.",
		photo_url: null,
		avg_rating: 4.5,
		total_checkins: 187,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// République
	{
		id: "p010",
		name: "Kouign-Amann",
		slug: "republique-kouign-amann",
		bakery_id: "b002",
		category: "Kouign-amann",
		description: "Caramelized Breton pastry. Thick, buttery, crackly crust with tender layers.",
		photo_url: null,
		avg_rating: 4.7,
		total_checkins: 198,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p011",
		name: "Miso White Chocolate Almond Croissant",
		slug: "miso-almond-croissant",
		bakery_id: "b002",
		category: "Croissants",
		description: "Almond croissant elevated with miso and white chocolate. Sweet-savory umami.",
		photo_url: null,
		avg_rating: 4.8,
		total_checkins: 167,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p012",
		name: "Bomboloni",
		slug: "republique-bomboloni",
		bakery_id: "b002",
		category: "Donuts",
		description: "Italian filled doughnuts with pastry cream or seasonal jam. Pillowy and rich.",
		photo_url: null,
		avg_rating: 4.5,
		total_checkins: 134,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p015",
		name: "Canelés",
		slug: "republique-caneles",
		bakery_id: "b002",
		category: "Cakes",
		description: "Bordeaux specialty: crispy caramelized shell, soft rum-vanilla custard center.",
		photo_url: null,
		avg_rating: 4.6,
		total_checkins: 112,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Fondry
	{
		id: "p018",
		name: "Kouign-Amann",
		slug: "fondry-kouign-amann",
		bakery_id: "b003",
		category: "Kouign-amann",
		description: "Tender spiraled bun that pulls apart like yarn. Arguably the best in LA.",
		photo_url: null,
		avg_rating: 4.9,
		total_checkins: 145,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p019",
		name: "Butter Croissant",
		slug: "fondry-butter-croissant",
		bakery_id: "b003",
		category: "Croissants",
		description: "Perfectly laminated, deeply caramelized. Serious butter game.",
		photo_url: null,
		avg_rating: 4.7,
		total_checkins: 178,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Modu Cafe
	{
		id: "p021",
		name: "Black Sesame Chocolate Cookie",
		slug: "black-sesame-choc-cookie",
		bakery_id: "b004",
		category: "Cookies",
		description: "Spongy, tangy, totally unique. Korean-California fusion at its best.",
		photo_url: null,
		avg_rating: 4.6,
		total_checkins: 89,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p022",
		name: "Perilla Leaf Lime Tart",
		slug: "perilla-lime-tart",
		bakery_id: "b004",
		category: "Tarts",
		description: "Lime tart with perilla leaf. Herbaceous and refreshing.",
		photo_url: null,
		avg_rating: 4.5,
		total_checkins: 67,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p024",
		name: "Miso Brown Butter Cookie",
		slug: "miso-brown-butter-cookie",
		bakery_id: "b004",
		category: "Cookies",
		description: "Brown butter cookie with white miso. Sweet-savory caramelized edges.",
		photo_url: null,
		avg_rating: 4.7,
		total_checkins: 95,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Tu Cha
	{
		id: "p025",
		name: "Mango Fruit Dessert",
		slug: "tu-cha-mango",
		bakery_id: "b005",
		category: "Cakes",
		description:
			"Trompe-l'oeil fruit-shaped dessert: chocolate shell, mango mousse, real fruit center.",
		photo_url: null,
		avg_rating: 4.8,
		total_checkins: 312,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p026",
		name: "Strawberry Fruit Dessert",
		slug: "tu-cha-strawberry",
		bakery_id: "b005",
		category: "Cakes",
		description: "Realistic strawberry-shaped dessert with strawberry mousse filling.",
		photo_url: null,
		avg_rating: 4.7,
		total_checkins: 278,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Lou
	{
		id: "p028",
		name: "Almond Croissant",
		slug: "lou-almond-croissant",
		bakery_id: "b006",
		category: "Croissants",
		description:
			"The best almond croissant in LA. Pre-order required. Rich almond cream, flaked almonds.",
		photo_url: null,
		avg_rating: 4.9,
		total_checkins: 203,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Arsicault
	{
		id: "p031",
		name: "Butter Croissant",
		slug: "arsicault-butter-croissant",
		bakery_id: "b007",
		category: "Croissants",
		description: "Bon Appétit's Bakery of the Year. Flaky, buttery, perfect. The GOAT.",
		photo_url: null,
		avg_rating: 4.9,
		total_checkins: 456,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p032",
		name: "Almond Croissant",
		slug: "arsicault-almond-croissant",
		bakery_id: "b007",
		category: "Croissants",
		description: "Rich almond frangipane, toasted almond flakes, powdered sugar.",
		photo_url: null,
		avg_rating: 4.8,
		total_checkins: 334,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p035",
		name: "Morning Bun",
		slug: "arsicault-morning-bun",
		bakery_id: "b007",
		category: "Croissants",
		description: "Orange zest and cinnamon sugar. Caramelized and addictive.",
		photo_url: null,
		avg_rating: 4.7,
		total_checkins: 212,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// B Patisserie
	{
		id: "p036",
		name: "Kouign-Amann Nature",
		slug: "b-patisserie-kouign-amann",
		bakery_id: "b008",
		category: "Kouign-amann",
		description: "The definitive California kouign-amann. Thick caramelized crust, buttery layers.",
		photo_url: null,
		avg_rating: 4.9,
		total_checkins: 389,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p039",
		name: "Pain Suisse",
		slug: "pain-suisse",
		bakery_id: "b008",
		category: "Croissants",
		description: "Chocolate chip-studded laminated pastry with pastry cream. Swiss-French classic.",
		photo_url: null,
		avg_rating: 4.6,
		total_checkins: 156,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p040",
		name: "Bostock",
		slug: "b-patisserie-bostock",
		bakery_id: "b008",
		category: "Brioche",
		description: "Twice-baked brioche with almond cream and orange blossom syrup.",
		photo_url: null,
		avg_rating: 4.5,
		total_checkins: 98,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p041",
		name: "Butter Mochi",
		slug: "butter-mochi",
		bakery_id: "b008",
		category: "Mochi",
		description: "Chewy, buttery mochi with a crispy edge. Hawaiian-French crossover.",
		photo_url: null,
		avg_rating: 4.6,
		total_checkins: 134,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Tartine
	{
		id: "p045",
		name: "Morning Bun",
		slug: "tartine-morning-bun",
		bakery_id: "b009",
		category: "Croissants",
		description: "Tartine's signature: cinnamon sugar with lemon twist. Extra brown and crispy.",
		photo_url: null,
		avg_rating: 4.8,
		total_checkins: 467,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p046",
		name: "Double Pain au Chocolat",
		slug: "tartine-pain-au-chocolat",
		bakery_id: "b009",
		category: "Croissants",
		description: "300-400 made daily, sells out by noon. Double the chocolate, extra brown.",
		photo_url: null,
		avg_rating: 4.7,
		total_checkins: 398,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p049",
		name: "Lemon Tart",
		slug: "tartine-lemon-tart",
		bakery_id: "b009",
		category: "Tarts",
		description: "Bright, tangy lemon curd in a crispy tart shell.",
		photo_url: null,
		avg_rating: 4.5,
		total_checkins: 145,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Butter & Crumble
	{
		id: "p053",
		name: "Pistachio Cardamom Croissant",
		slug: "pistachio-cardamom-croissant",
		bakery_id: "b010",
		category: "Croissants",
		description:
			"The evolution of the pistachio trend. Warm cardamom meets bright pistachio cream.",
		photo_url: null,
		avg_rating: 4.8,
		total_checkins: 234,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Grand Opening
	{
		id: "p056",
		name: "Coconut Scroll",
		slug: "coconut-scroll",
		bakery_id: "b011",
		category: "Croissants",
		description:
			"Laminated like a croissant, inspired by Chinese cocktail bun, filled with frangipane. Peak SF.",
		photo_url: null,
		avg_rating: 4.7,
		total_checkins: 178,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Third Culture
	{
		id: "p058",
		name: "OG Mochi Muffin",
		slug: "og-mochi-muffin",
		bakery_id: "b012",
		category: "Mochi",
		description: "The original since 2016. Crunchy outside, impossibly chewy inside. Gluten free.",
		photo_url: null,
		avg_rating: 4.7,
		total_checkins: 356,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p059",
		name: "Ube Mochi Muffin",
		slug: "ube-mochi-muffin",
		bakery_id: "b012",
		category: "Mochi",
		description: "Purple yam version. Vibrant color, earthy-sweet flavor, same legendary chew.",
		photo_url: null,
		avg_rating: 4.8,
		total_checkins: 289,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Golden Gate
	{
		id: "p063",
		name: "Egg Custard Tart",
		slug: "golden-gate-egg-tart",
		bakery_id: "b013",
		category: "Tarts",
		description:
			"Legendary Chinatown egg tart. Silky custard, flaky shell. Worth the gamble on whether they're open.",
		photo_url: null,
		avg_rating: 4.9,
		total_checkins: 512,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// Cream Pan
	{
		id: "p065",
		name: "Strawberry Croissant",
		slug: "cream-pan-strawberry-croissant",
		bakery_id: "b014",
		category: "Croissants",
		description:
			"Cream Pan's iconic item. Fresh strawberries, custard cream, flaky croissant. Japanese-French precision.",
		photo_url: null,
		avg_rating: 4.8,
		total_checkins: 423,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p066",
		name: "Chocolate Cornet",
		slug: "chocolate-cornet",
		bakery_id: "b014",
		category: "Bread",
		description: "Horn-shaped bread filled with rich chocolate cream. Japanese bakery classic.",
		photo_url: null,
		avg_rating: 4.4,
		total_checkins: 156,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},

	// 61 Hundred Bread
	{
		id: "p070",
		name: "Sourdough Croissant",
		slug: "sourdough-croissant-61",
		bakery_id: "b015",
		category: "Croissants",
		description: "Long-fermented sourdough lamination. Complex, tangy, deeply flaky.",
		photo_url: null,
		avg_rating: 4.7,
		total_checkins: 98,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
	{
		id: "p072",
		name: "Brown Butter Financier",
		slug: "brown-butter-financier",
		bakery_id: "b015",
		category: "Cakes",
		description: "Nutty brown butter, crispy edges, tender almond center.",
		photo_url: null,
		avg_rating: 4.5,
		total_checkins: 67,
		created_by: "system",
		created_at: "2026-01-01T00:00:00Z",
	},
];

// Mock users for social feed
export const MOCK_USERS: Profile[] = [
	{
		id: "u001",
		username: "maya_bakes",
		display_name: "Maya Chen",
		avatar_url: null,
		bio: "Croissant hunter. SF born.",
		favorite_categories: ["Croissants", "Kouign-amann", "Tarts"],
		level: 5,
		xp: 480,
		total_checkins: 47,
		created_at: "2026-01-15T00:00:00Z",
		updated_at: "2026-03-01T00:00:00Z",
	},
	{
		id: "u002",
		username: "pastryjosh",
		display_name: "Josh Rivera",
		avatar_url: null,
		bio: "Always in line at Porto's",
		favorite_categories: ["Empanadas", "Cookies", "Cakes"],
		level: 3,
		xp: 220,
		total_checkins: 23,
		created_at: "2026-02-01T00:00:00Z",
		updated_at: "2026-03-05T00:00:00Z",
	},
	{
		id: "u003",
		username: "the.flour.girl",
		display_name: "Aria Kim",
		avatar_url: null,
		bio: "Mochi everything 🍡",
		favorite_categories: ["Mochi", "Croissants", "Donuts"],
		level: 4,
		xp: 340,
		total_checkins: 35,
		created_at: "2026-01-20T00:00:00Z",
		updated_at: "2026-03-08T00:00:00Z",
	},
	{
		id: "u004",
		username: "dough.or.die",
		display_name: "Sam Torres",
		avatar_url: null,
		bio: "Sourdough purist. OC local.",
		favorite_categories: ["Bread", "Croissants"],
		level: 2,
		xp: 130,
		total_checkins: 14,
		created_at: "2026-02-10T00:00:00Z",
		updated_at: "2026-03-07T00:00:00Z",
	},
];

// Mock check-ins for feed
export const MOCK_CHECKINS: (CheckIn & { user: Profile; pastry: Pastry; bakery: Bakery })[] = [
	{
		id: "c001",
		user_id: "u001",
		pastry_id: "p036",
		bakery_id: "b008",
		rating: 5,
		notes: "The caramelized crust shatters into a thousand buttery layers. This is the one.",
		photo_url: null,
		flavor_tags: ["Butter", "Caramelized"],
		taste_ratings: null,
		created_at: "2026-03-09T08:30:00Z",
		user: {
			id: "u001",
			username: "maya_bakes",
			display_name: "Maya Chen",
			avatar_url: null,
			bio: null,
			favorite_categories: ["Croissants", "Kouign-amann"],
			level: 5,
			xp: 480,
			total_checkins: 47,
			created_at: "",
			updated_at: "",
		},
		pastry: PASTRIES.find((p) => p.id === "p036")!,
		bakery: BAKERIES.find((b) => b.id === "b008")!,
	},
	{
		id: "c002",
		user_id: "u002",
		pastry_id: "p001",
		bakery_id: "b001",
		rating: 5,
		notes: "Stocked up on a dozen. The guava-to-cheese ratio is perfect every single time.",
		photo_url: null,
		flavor_tags: ["Guava", "Butter"],
		taste_ratings: null,
		created_at: "2026-03-09T07:15:00Z",
		user: {
			id: "u002",
			username: "pastryjosh",
			display_name: "Josh Rivera",
			avatar_url: null,
			bio: null,
			favorite_categories: ["Empanadas"],
			level: 3,
			xp: 220,
			total_checkins: 23,
			created_at: "",
			updated_at: "",
		},
		pastry: PASTRIES.find((p) => p.id === "p001")!,
		bakery: BAKERIES.find((b) => b.id === "b001")!,
	},
	{
		id: "c003",
		user_id: "u003",
		pastry_id: "p059",
		bakery_id: "b012",
		rating: 5,
		notes: "The purple color! The chew! Third Culture never misses.",
		photo_url: null,
		flavor_tags: ["Ube", "Chewy"],
		taste_ratings: null,
		created_at: "2026-03-08T16:00:00Z",
		user: {
			id: "u003",
			username: "the.flour.girl",
			display_name: "Aria Kim",
			avatar_url: null,
			bio: null,
			favorite_categories: ["Mochi"],
			level: 4,
			xp: 340,
			total_checkins: 35,
			created_at: "",
			updated_at: "",
		},
		pastry: PASTRIES.find((p) => p.id === "p059")!,
		bakery: BAKERIES.find((b) => b.id === "b012")!,
	},
	{
		id: "c004",
		user_id: "u001",
		pastry_id: "p053",
		bakery_id: "b010",
		rating: 4,
		notes: "Worth the line. Cardamom is subtle but it makes the whole thing sing.",
		photo_url: null,
		flavor_tags: ["Pistachio", "Cardamom", "Butter"],
		taste_ratings: null,
		created_at: "2026-03-08T09:45:00Z",
		user: {
			id: "u001",
			username: "maya_bakes",
			display_name: "Maya Chen",
			avatar_url: null,
			bio: null,
			favorite_categories: ["Croissants"],
			level: 5,
			xp: 480,
			total_checkins: 47,
			created_at: "",
			updated_at: "",
		},
		pastry: PASTRIES.find((p) => p.id === "p053")!,
		bakery: BAKERIES.find((b) => b.id === "b010")!,
	},
	{
		id: "c005",
		user_id: "u004",
		pastry_id: "p070",
		bakery_id: "b015",
		rating: 5,
		notes:
			"Finally open! The sourdough tang with that lamination — this is OC's answer to Tartine.",
		photo_url: null,
		flavor_tags: ["Sourdough", "Butter", "Flaky"],
		taste_ratings: null,
		created_at: "2026-03-07T10:30:00Z",
		user: {
			id: "u004",
			username: "dough.or.die",
			display_name: "Sam Torres",
			avatar_url: null,
			bio: null,
			favorite_categories: ["Bread", "Croissants"],
			level: 2,
			xp: 130,
			total_checkins: 14,
			created_at: "",
			updated_at: "",
		},
		pastry: PASTRIES.find((p) => p.id === "p070")!,
		bakery: BAKERIES.find((b) => b.id === "b015")!,
	},
	{
		id: "c006",
		user_id: "u003",
		pastry_id: "p025",
		bakery_id: "b005",
		rating: 5,
		notes: "Almost too pretty to eat. The mango mousse inside is absurdly good.",
		photo_url: null,
		flavor_tags: ["Chocolate", "Fruity"],
		taste_ratings: null,
		created_at: "2026-03-07T14:20:00Z",
		user: {
			id: "u003",
			username: "the.flour.girl",
			display_name: "Aria Kim",
			avatar_url: null,
			bio: null,
			favorite_categories: ["Mochi", "Cakes"],
			level: 4,
			xp: 340,
			total_checkins: 35,
			created_at: "",
			updated_at: "",
		},
		pastry: PASTRIES.find((p) => p.id === "p025")!,
		bakery: BAKERIES.find((b) => b.id === "b005")!,
	},
];

// Helper to get bakery by id
export function getBakery(id: string) {
	return BAKERIES.find((b) => b.id === id);
}

// Helper to get pastries by bakery
export function getPastriesByBakery(bakeryId: string) {
	return PASTRIES.filter((p) => p.bakery_id === bakeryId);
}

// Helper to get pastry by id
export function getPastry(id: string) {
	return PASTRIES.find((p) => p.id === id);
}

// Trending: top pastries by check-in count
export function getTrendingPastries(limit = 6) {
	return [...PASTRIES].sort((a, b) => b.total_checkins - a.total_checkins).slice(0, limit);
}

// Search pastries and bakeries
export function search(query: string) {
	const q = query.toLowerCase();
	const pastries = PASTRIES.filter(
		(p) =>
			p.name.toLowerCase().includes(q) ||
			p.category.toLowerCase().includes(q) ||
			(p.description?.toLowerCase().includes(q) ?? false),
	);
	const bakeries = BAKERIES.filter(
		(b) =>
			b.name.toLowerCase().includes(q) ||
			(b.city?.toLowerCase().includes(q) ?? false) ||
			(b.address?.toLowerCase().includes(q) ?? false),
	);
	return { pastries, bakeries };
}

// Get pastries by category
export function getPastriesByCategory(category: string) {
	return PASTRIES.filter((p) => p.category === category);
}

// Get check-in by id
export function getCheckIn(id: string) {
	return MOCK_CHECKINS.find((c) => c.id === id);
}

// Get check-ins for a pastry
export function getCheckInsForPastry(pastryId: string) {
	return MOCK_CHECKINS.filter((c) => c.pastry_id === pastryId);
}

// Get check-ins for a bakery
export function getCheckInsForBakery(bakeryId: string) {
	return MOCK_CHECKINS.filter((c) => c.bakery_id === bakeryId);
}

// Get check-ins for a user
export function getCheckInsForUser(userId: string) {
	return MOCK_CHECKINS.filter((c) => c.user_id === userId);
}

// Get user by id
export function getUser(id: string) {
	return MOCK_USERS.find((u) => u.id === id);
}

// Get the "current" user (u001 for demo)
export function getCurrentUser() {
	return MOCK_USERS[0];
}

// Get unique bakeries a user visited
export function getBakeriesVisited(userId: string) {
	const bakeryIds = new Set(
		MOCK_CHECKINS.filter((c) => c.user_id === userId).map((c) => c.bakery_id),
	);
	return BAKERIES.filter((b) => bakeryIds.has(b.id));
}
