export interface PastryCategory {
	name: string;
	icon: string;
}

export const PASTRY_CATEGORIES: PastryCategory[] = [
	{ name: "Croissants", icon: "Croissant" },
	{ name: "Cookies", icon: "Cookie" },
	{ name: "Cakes", icon: "CakeSlice" },
	{ name: "Tarts", icon: "Cherry" },
	{ name: "Bread", icon: "Wheat" },
	{ name: "Donuts", icon: "Circle" },
	{ name: "Pies", icon: "PieChart" },
	{ name: "Macarons", icon: "Circle" },
	{ name: "Mochi", icon: "Circle" },
	{ name: "Muffins", icon: "CupSoda" },
	{ name: "Scones", icon: "Triangle" },
	{ name: "Brownies", icon: "Square" },
	{ name: "Eclairs & Choux", icon: "Droplet" },
	{ name: "Kouign-amann", icon: "Flame" },
	{ name: "Conchas", icon: "Shell" },
	{ name: "Empanadas", icon: "Sandwich" },
	{ name: "Danish", icon: "Flower" },
	{ name: "Cinnamon Rolls", icon: "RefreshCw" },
	{ name: "Brioche", icon: "Egg" },
];

export const FLAVOR_TAGS = [
	"Butter",
	"Almond",
	"Chocolate",
	"Pistachio",
	"Matcha",
	"Ube",
	"Brown Butter",
	"Sourdough",
	"Black Sesame",
	"Hojicha",
	"Earl Grey",
	"Guava",
	"Yuzu",
	"Miso Caramel",
	"Passionfruit",
	"Tahini",
	"Cinnamon",
	"Vanilla",
	"Lemon",
	"Raspberry",
	"Strawberry",
	"Coconut",
	"Corn Masa",
	"Dulce de Leche",
	"Olive Oil",
	"Honey",
	"Cardamom",
	"Fig",
] as const;

export const TEXTURE_TAGS = [
	"Flaky",
	"Crispy",
	"Gooey",
	"Chewy",
	"Pillowy",
	"Buttery",
	"Crunchy",
	"Creamy",
	"Tender",
	"Caramelized",
	"Underbaked",
	"Sticky",
	"Crackly",
	"Pull-apart",
	"Layered",
] as const;
